name: app_walkie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  # HTTP y API
  dio: ^5.4.0
  
  # Socket.io para WebRTC y señalización
  socket_io_client: ^2.0.3+1

  # WebRTC

  # Almacenamiento local (guardar token y conversaciones)
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0

  # Manejo de estado
  provider: ^6.1.1

  # UI
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  record: ^6.2.0
  audioplayers: ^6.6.0
  flutter_webrtc: ^1.3.1
  audio_session: ^0.2.2
  flutter_background: ^1.3.1
  audio_waveforms: ^2.0.2
  flutter_overlay_window: ^0.5.0
  speech_to_text: any
  geolocator: any
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_size: 21

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/beep.mp3
